dist: trusty
sudo: false
language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3
  - ruby-head
before_install:
  - gem install bundler -v 1.16.1
  - unset _JAVA_OPTIONS
  - mkdir ./tmp
matrix:
  allow_failures:
    - rvm: 2.3
    - rvm: ruby-head
